### ISSUE TITLE
Cannot debug an Electron application with TestCafe

### ISSUE THREAD

**Issue by vicentesaettone09** [DevExpress/testcafe-browser-provider-electron#81] opened 2021-04-21 13:56 UTC
**Description:**

We are trying to debug an Electron application with TestCafe
Since the upgrade to Electron 11.2.0 and testcafe-browser-provider-electron 0.0.16 we cannot do that anymore.

**Issue:**

We are not able to debug the application using VSCode.

**Error:**

![image](https://user-images.githubusercontent.com/46244458/115565062-6eed4a80-a28f-11eb-98a9-adf94f216b70.png)

**Tested in:**

**Electron 8.3.3 - testcafe 1.8.1 - provider 0.0.14:**
The e2e run as expected and I was able to debug with vscode (electron and chrome) with no errors

**Electron 8.3.3 - testcafe 1.8.1 - provider 0.0.16:**
The e2e run as expected and I was able to debug with vscode (electron and chrome) with no errors

**Electron 8.3.3 - testcafe 1.13.0 - provider 0.0.16:**
The e2e run as expected and I was able to debug with vscode (electron and chrome) with no errors

**Electron 11.2.0- testcafe 1.13.0- provider 0.0.16:**
The debugger works with chrome but does not work with electron

**Electron 12.0.1- testcafe 1.13.0- provider 0.0.16:**
The debugger works with chrome but does not work with electron

**Questions:**

- Is there a way to debug application using VSCode with Electron using Electron@11.2.0, testcafe@1.13.0 and testcafe-browser-provider-electron@0.0.16?
-  We found this error related to this topic: https://github.com/DevExpress/testcafe-browser-provider-electron/issues/59, should we wait for a provider update?
- We have pending an electron 12 update, this error is going to be kept in that version?

These are the current config for our test:
**Dependencies:**

```json
"electron": "11.2.0"
"electron-builder": "20.31.2"
"testcafe": "1.13.0"
"testcafe-browser-provider-electron": "0.0.16"
```

launch.json:

```json
{
 "type": "node",
 "request": "launch",
 "name": "Run E2E tests on Electron",
 "program": "${workspaceFolder}/node_modules/testcafe/bin/testcafe.js",
 "env": {
 "NODE_ENV": "sample_value",
 },
 "args": [
 "electron",
 "components/***.ts",
 "tests/common/**/*.ts",
 "tests/performance/common/**/*.ts",
 "--reporter-app-name=Debug-E2E-UI",
 "--reporter-app-version=0.0.0",
 ],
 "cwd": "${workspaceFolder}/projects/e2e-ui",
}
```

**Comment by Farfurix** [comment] 2021-04-22 08:20
@vicentesaettone09 

Hello,

I reproduced the connection issue in our tests after updating the repository dependencies.

> We found this error related to this topic: #59, should we wait for a provider update?

It looks like a similar issue. Yes, you need to wait until the #59 issue is resolved. So, I will close this issue as a duplicate.

> We have pending an electron 12 update, this error is going to be kept in that version?

We haven't tested Electron v12 yet. The last version we tested was [v11.0.3](https://github.com/DevExpress/testcafe-browser-provider-electron/blob/master/package.json#L56).

**Closed by Farfurix** 2021-04-22 08:21 UTC
Labels: STATE: Need response
